---
- name: Postgres
  hosts: node1,node2,barman
  become: yes
  tasks:
    - name: Add mirrorlist to repo
      shell: |
        cd /etc/yum.repos.d/ | sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*

    - name: Add mirrorlist to repo2
      shell: |
        cd /etc/yum.repos.d/ | sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  #Устанавливаем vim и telnet (для более удобной работы с хостами)
    - name: install base tools
      dnf:
        name:
          - vim
          - telnet
        state: present
        update_cache: true

#Запуск ролей install_postgres и postgres_replication на хостах node1 и node2
- name: install postgres 14 and set up replication
  hosts: node1,node2
  become: yes
  roles:
    - install_postgres
    - postgres_replication

#Запуск роли install_barman на всех хостах
- name: set up backup
  hosts: node1,node2,barman
  become: yes
  roles:
    - install_barman
...
